### ISSUE TITLE
Delete an item from Wishlist

### ISSUE THREAD

**Issue by arunimamitra** [CSCI-GA-2820-SP24-003/wishlists#5]
**As a** user
**I need** the ability to delete a wishlist item
**So that** I can keep the items I desire the most.
   
 ### Details and Assumptions
 * Wishlist database is not empty
 * Wishlist should not have an item limit
 * Path is /wishlists/{id}/items/{id}
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given wishlist is not empty 
 When I delete an item from the wishlist
 Then the wishlist item should be deleted and the database should be automatically updated
 User is notified of the changes
```
 ```gherkin
 Given a wishlist item is discontinued, 
 Then the wishlist item should be deleted and the user should be notified of the changes.
```

**Comment by SeanP0110** [comment]
Inserted Acceptance Criteria for discontinued item.
