### ISSUE TITLE
Add action route to publish a wishlist

### ISSUE THREAD

**Issue by arunimamitra** [CSCI-GA-2820-SP24-003/wishlists#52]
**As a** user
**I need** the functionality to publish my wishlist 
**So that** I can share my wishlist by making it publicly visible
   
 ### Details and Assumptions
 * is_public boolean flag needs to be true when user wants to publish wishlist
 * DB schema should be unaffected by this change
 * The is_public flag has default value = false
 * Endpoint is /wishlists/{id}/publish
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the wishlist service
 When a user wants to publish a wishlist
 Then the database should reflect is_public as True for the specific wishlist.
```

**Comment by Animesh-Ramesh** [comment]
Add default is_public to false
